In [1]:
import jax.numpy as jnp

In [5]:
import jax.numpy as jnp

tensor = jnp.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
     [13, 14, 15, 16]],

    [[17, 18, 19, 20],
     [21, 22, 23, 24],
     [25, 26, 27, 28],
     [29, 30, 31, 32]]
])

print(tensor.shape)  # (2, 4, 4)

tensor


(2, 4, 4)


Array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]], dtype=int32)

In [16]:
x = jnp.array([1,2, 1, 2])
x

Array([1, 2, 1, 2], dtype=int32)

In [17]:
tensor*x[None, :, None]

Array([[[ 1,  2,  3,  4],
        [10, 12, 14, 16],
        [ 9, 10, 11, 12],
        [26, 28, 30, 32]],

       [[17, 18, 19, 20],
        [42, 44, 46, 48],
        [25, 26, 27, 28],
        [58, 60, 62, 64]]], dtype=int32)

In [18]:
M = jnp.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16]])
M

Array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)

In [19]:
t = jnp.array([1,2])

In [20]:
t

Array([1, 2], dtype=int32)

In [25]:
(M*t[:, None, None]).sum(axis=0)

Array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48]], dtype=int32)