In [2]:
import jax.numpy as jnp

In [4]:
arr = jnp.array([[1, 2, 3], 
                [2, 4, 6]])


diff = jnp.diff(arr, axis=1)
print(diff)


log_diff = jnp.log(diff)

print(log_diff)

print(jnp.exp(log_diff))

print("arr", arr[:, :1])

# rebuild arr from its first column + the (log) increments
first = arr[:, :1]
print(first)
arr_2 = jnp.concatenate(
    [first, first + jnp.cumsum(jnp.exp(log_diff), axis=1)], axis=1
)

print(arr_2)


[[1 1]
 [2 2]]
[[0.        0.       ]
 [0.6931472 0.6931472]]
[[1. 1.]
 [2. 2.]]
arr [[1]
 [2]]
[[1]
 [2]]
[[1. 2. 3.]
 [2. 4. 6.]]
